# fly.toml app configuration file generated for notion-manager
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "notion-manager"
primary_region = "sin"  # Singapore - closest to Malaysia

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # IMPORTANT: Prevent auto-sleep
  auto_start_machines = true
  min_machines_running = 1    # Keep at least 1 machine running

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  PORT = "3000"
  NODE_ENV = "production"
